version: '3'
services:
  dev:
    build: support/dev
    volumes:
      - .:/work
      - node-14-node-modules:/work/node_modules
      - yarn-cache-14:/tmp/yarn-cache
    working_dir: /work
    environment:
      yarn_cache_folder: /tmp/yarn-cache

volumes:
  node-14-node-modules:
    external: true
  yarn-cache-14:
    external: true
