services:
  dev:
    build: support/dev
    volumes:
      - .:/work
      - node-18-node-modules:/work/node_modules
      - yarn-cache-18:/tmp/yarn-cache
    working_dir: /work
    environment:
      yarn_cache_folder: /tmp/yarn-cache

volumes:
  node-18-node-modules:
    external: true
  yarn-cache-18:
    external: true
