#!/bin/bash -eu

cd $(dirname $0)/..

# Clean up at the end
trap "docker-compose down --volumes --remove-orphans" 0

# Create volume
docker volume create --name node-12-node-modules > /dev/null
docker volume create --name yarn-cache-12 > /dev/null

# build the service
docker-compose build dev

# Run dev script or use what is passed in as arguments
docker-compose run --rm dev "$@"
